[package]
name = "fx_cef_internal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bindgen = "0.70.1"
bzip2 = "0.4.4"
flate2 = "1.0.34"
reqwest = { version = "0.12.8", features = ["blocking"] }
tar = "0.4.42"

